/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

/**
 *
 * @author alumno
 */
public class pago extends javax.swing.JFrame {

    /**
     * Creates new form pago
     */
    public pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombre = new javax.swing.JLabel();
        lbNumeroTarjeta = new javax.swing.JLabel();
        lbCodigoSeguridad = new javax.swing.JLabel();
        lbCaducidad = new javax.swing.JLabel();
        etMes = new javax.swing.JTextField();
        etNombreTitular = new javax.swing.JTextField();
        etNumeroTarjeta = new javax.swing.JTextField();
        etCodigoSeguridad = new javax.swing.JTextField();
        etDia = new javax.swing.JTextField();
        lbPagoConTarjeta = new javax.swing.JLabel();
        lbAceptamos = new javax.swing.JLabel();
        spCiudad = new javax.swing.JSpinner();
        lbCiudad = new javax.swing.JLabel();
        btnOtrosPagos = new javax.swing.JToggleButton();
        btnCofirmarPago = new javax.swing.JToggleButton();
        lbImagenVisa = new javax.swing.JLabel();
        lbMensajeConfirmar = new javax.swing.JLabel();
        lbImagenTarjetas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbNombre.setText("Nombre del Titular");

        lbNumeroTarjeta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbNumeroTarjeta.setText("Numero de Tarjeta");

        lbCodigoSeguridad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbCodigoSeguridad.setText("CVV (Código de seguridad)");

        lbCaducidad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbCaducidad.setText("Fecha de Caducidad");

        lbPagoConTarjeta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPagoConTarjeta.setForeground(new java.awt.Color(51, 0, 255));
        lbPagoConTarjeta.setText("Pago con Tarjeta");

        lbAceptamos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbAceptamos.setForeground(new java.awt.Color(51, 51, 0));
        lbAceptamos.setText("Aceptamos:");

        lbCiudad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbCiudad.setText("Seleccione Ciudad");

        btnOtrosPagos.setText("Otro Metodo de Pago");

        btnCofirmarPago.setText("Confirmar Pedido");

        lbImagenVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gvillena/ttttttttttttttttttttttttt (2).png"))); // NOI18N

        lbMensajeConfirmar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 10)); // NOI18N
        lbMensajeConfirmar.setForeground(new java.awt.Color(255, 0, 51));
        lbMensajeConfirmar.setText("Confirm your order of 32,66 $ by clicking the button \"Confirm my order\"");

        lbImagenTarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gvillena/visaaaaaaaaaaaaaa (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPagoConTarjeta)
                        .addGap(129, 129, 129)
                        .addComponent(lbAceptamos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImagenTarjetas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCaducidad)
                            .addComponent(lbCiudad)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombre)
                                    .addComponent(lbNumeroTarjeta))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spCiudad)
                                    .addComponent(etNumeroTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(etNombreTitular)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etMes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(etDia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCodigoSeguridad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(lbImagenVisa)
                        .addGap(152, 152, 152))))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnOtrosPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCofirmarPago)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbMensajeConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPagoConTarjeta)
                        .addComponent(lbAceptamos))
                    .addComponent(lbImagenTarjetas))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombre)
                            .addComponent(etNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumeroTarjeta)
                            .addComponent(etNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigoSeguridad)
                            .addComponent(etCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCaducidad)
                            .addComponent(etMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCiudad)
                            .addComponent(spCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbImagenVisa))
                .addGap(15, 15, 15)
                .addComponent(lbMensajeConfirmar)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtrosPagos)
                    .addComponent(btnCofirmarPago))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCofirmarPago;
    private javax.swing.JToggleButton btnOtrosPagos;
    private javax.swing.JTextField etCodigoSeguridad;
    private javax.swing.JTextField etDia;
    private javax.swing.JTextField etMes;
    private javax.swing.JTextField etNombreTitular;
    private javax.swing.JTextField etNumeroTarjeta;
    private javax.swing.JLabel lbAceptamos;
    private javax.swing.JLabel lbCaducidad;
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbCodigoSeguridad;
    private javax.swing.JLabel lbImagenTarjetas;
    private javax.swing.JLabel lbImagenVisa;
    private javax.swing.JLabel lbMensajeConfirmar;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumeroTarjeta;
    private javax.swing.JLabel lbPagoConTarjeta;
    private javax.swing.JSpinner spCiudad;
    // End of variables declaration//GEN-END:variables
}
